home-assistant-libs/aioshelly

aioshelly/__init__.py

This PR:
- adds some missing model names (models with relays)
- sorts model names

Add some missing model names

---

README.md

based on https://github.com/home-assistant-libs/aioshelly/blob/main/aioshelly/__init__.py#L8-L17

Add supported devices list

---

aioshelly/__init__.py
requirements-test.txt
verify.py

Adds a verify script that downloads all Coiot examples from the Shelly website and checks to make sure that we can parse them. This will also make it easy to use as a reference. 
Example output:
```
Shelly 1 SHSW-1 no-addon
relay {'output': 0, 'input': 0, 'inputEvent': '', 'inputEventCnt': 0}
sensor {'extTemp': None, 'humidity': None, 'extInput': None}
sensor {'extTemp': None}
sensor {'extTemp': None}
device {'cfgChanged': 0}
--------------------------------
Shelly 1 SHSW-1 with-dht22
relay {'output': 0, 'input': 0, 'inputEvent': '', 'inputEventCnt': 0}
sensor {'extTemp': 21.6, 'humidity': 55.4, 'extInput': None}
sensor {'extTemp': None}
sensor {'extTemp': None}
device {'cfgChanged': 0}
--------------------------------
Shelly 1 SHSW-1 with-ds1820
relay {'output': 0, 'input': 0, …
```

Add verify script

---

aioshelly/__init__.py

The rgbw2 has slightly different HTTP paths to control the light

Route rgbw2 set state commands correctly

---

aioshelly/__init__.py
example.py

We have a few parameter name issues after #17 
This PR fixes these mistakes.

Fix parameter names after PR#17

---

setup.py

This PR bumps version to 0.5.0 to make sure we're using the current code.

Bump version to 0.5.0

---

aioshelly/__init__.py

This PR adds `Shelly 1L` model name.

Add Shelly 1L model name

---

aioshelly/__init__.py

This PR adds new `SHCB-1` bulb model.

Add SHCB-1 model

---

aioshelly/coap.py
mypy.ini
pylintrc
requirements.txt

This PR add multicast listener to all IPv4 network interfaces.
Fixes #52

Add multicast listener to all network interfaces

---

aioshelly/__init__.py

This PR adds `SHBTN-2` model - Shelly Button1 hardware version 2.

Add SHBTN-2 model

---

aioshelly/coap.py

Allow socket port personalization in order to to allow more than 1 instance of HA run on the same docker host.

Allow socket port customization

---

aioshelly/coap.py

Fixed a wrong log description and added the CoAP packet code.

Improve logging

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
requirements-dev.txt

Add docker files to allow a easy "`Remote-Containers: Clone Repository in Container Volume`" from VScode

Add docker files

---

README.md

Add note about breaking changes for Gen1
Update Gen1 example and add Gen2 example

Update README.md file for Gen2 support

---

aioshelly/common.py
aioshelly/wsrpc.py
setup.py

- Fix `WsRPC` disconnect
- Fix `get_info` return type
- Bump version to 1.0.1

Fix RpcDevice shutdown

---

aioshelly/const.py
aioshelly/wsrpc.py

Add heartbeat to WsRPC to improve detection of disconnected device

Add heartbeat to WsRPC

---

setup.py

* Check min fw version for gen2 devices (#143) @chemelli74
* Add heartbeat to WsRPC (#142) @thecode

Bump version to 1.0.2

---

aioshelly/block_device.py

Improve logging for debug purposes

Add aiohttp debug logging

---

aioshelly/block_device.py
aioshelly/rpc_device.py
pylintrc

this will add `trigger_reboot()`  to block and rpc devices.

Add trigger reboot call

---

setup.py

* Fix - prevent setting resolves during disconnect or at startup (#185) @thecode
* Bump pre-commit from 2.16.0 to 2.17.0 (#184) @dependabot
* Bump mypy from 0.930 to 0.931 (#183) @dependabot

Bump version to 1.0.8

---

aioshelly/exceptions.py
aioshelly/rpc_device.py
aioshelly/wsrpc.py

Implement Shelly gen2 authentication support, continue work by @figadore https://github.com/home-assistant-libs/aioshelly/pull/192
Thanks @figadore and @kzyapkov

Add Shelly gen2 authentication support

---

README.md

- Remove comment from release 1.0.0
- Update `README.md` with changes for exceptions handling and Gen2 class init

Update README for exceptions changes

---

aioshelly/rpc_device.py

Fix RPC async init, due to a bug found in https://github.com/home-assistant/core/issues/80902
if we get to this line:
https://github.com/home-assistant-libs/aioshelly/blob/5208eba1d81873b764495a2fd41180a75337ebf4/aioshelly/rpc_device.py#L96
With for the first time and we don't already have a previous status we drop it. This is due to an edge case that we received an event from the device before init (event is not a status)
Sleeping Gen2 devices always wake up and sends `NotifyFullStatus`  so we don't merge we just store it.
However my device now sends `NotifyStatus` with just firmware update status which is enough to wake it up and trigger init but status is dropped since it is partial and we don't have previous status.
Recently I made a change not to fetch status on async init, it worked …

Fix RPC async init

---

setup.py

**Merge after https://github.com/home-assistant-libs/aioshelly/pull/272 is merged**

Bump version to 4.1.1

---

aioshelly/ble/__init__.py
aioshelly/ble/const.py
aioshelly/rpc_device.py
requirements.txt
setup.py

Split out from https://github.com/home-assistant/core/pull/82007

Add BLE support

---

aioshelly/ble/__init__.py
aioshelly/const.py
aioshelly/rpc_device.py
aioshelly/wsrpc.py

BREAKING CHANGE:
The signature has changed for the `RpcDevice` callbacks is now
`(RpcDevice, UpdateType)`

Add UpdateType to the RPC callback to notify when disconnected

---

aioshelly/rpc_device/wsrpc.py

Make receive_json_or_raise a normal function

---

aioshelly/rpc_device/device.py
setup.py

Apply https://github.com/home-assistant-libs/aioshelly/pull/298 to main branch

Fix RPC trigger reboot

---

aioshelly/rpc_device/wsrpc.py

If there are a lot of bluetooth packets coming over the wire we want the shelly to be able to empty its buffer as fast as possible if the event loop is busy so we increase the buffer size a bit to reduce the memory pressure on the shelly

Reduce pressure on shelly device by increasing receive buffer

---

example.py

Fix example to support `UpdateType` added in https://github.com/home-assistant-libs/aioshelly/pull/283

Fix example device update callback

---

aioshelly/block_device/device.py
aioshelly/rpc_device/device.py
example.py

- Add name property to have common API for Gen1 & Gen2
- Cleanup properties
- Update example to show device name

Add name property and cleanup properties

---

setup.py

Create release for https://github.com/home-assistant-libs/aioshelly/pull/376

Bump version to 5.3.2

---

aioshelly/rpc_device/device.py
aioshelly/rpc_device/models.py
example.py

To test:
```bash
python example.py --ip 192.168.1.75 -g2 -i -uw "ws://192.168.1.10:8123/api/shelly/ws"
```

Add outbound websocket update

---

aioshelly/rpc_device/wsrpc.py

Gather asyncio tasks in a collection

---

aioshelly/block_device/__init__.py
aioshelly/block_device/coap.py
aioshelly/block_device/device.py
aioshelly/rpc_device/__init__.py
aioshelly/rpc_device/device.py
example.py

```python
class BlockUpdateType(Enum):
"""Block Update type."""
COAP_PERIODIC = auto()
COAP_REPLY = auto()
INITIALIZED = auto()
```
Rename RPC Device `UpdateType` to `RpcUpdateType`
Add `BlockUpdateType` to Block Device update callbacks

Add block device update type

---

requirements_dev.txt

Fix dev requirements

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
script/environment.sh

Readd pip install env
cc: @MartinHjelmare

Fix devcontainer setup

---

aioshelly/block_device/device.py
aioshelly/common.py
aioshelly/rpc_device/wsrpc.py
requirements.txt

Adds aditional check when parsing ip adresses to check for ipv6 adresses and append "[" brackets if so.
Change URLs to be build by aio URL builder automatically adding brackets if applicable 
Fixes #433

Add aditional ip parsing for ipv6 url brackets

---

aioshelly/rpc_device/wsrpc.py

https://github.com/home-assistant/core/issues/105273

Fix concurrent call to receive

---

setup.py

needs https://github.com/home-assistant-libs/aioshelly/pull/478

Bump version to 8.0.0

---

setup.py

Release mainly to have https://github.com/home-assistant-libs/aioshelly/pull/501 in beta

Bump version to 8.0.2

---

setup.py

Release for https://github.com/home-assistant-libs/aioshelly/pull/505

Bump version to 8.1.0

---

aioshelly/block_device/coap.py

Change parameters order to allow backward compatibility

Fix backward params compatibility

---

aioshelly/block_device/coap.py
aioshelly/rpc_device/wsrpc.py
ruff.toml
tools/common/__init__.py
tools/verify.py

Related to https://github.com/home-assistant-libs/aioshelly/pull/527

Drop Python 3.10 for ruff

---

aioshelly/block_device/device.py
aioshelly/rpc_device/device.py
aioshelly/rpc_device/wsrpc.py

Replace async_timeout with asyncio.timeout

---

aioshelly/block_device/device.py
aioshelly/rpc_device/device.py

To help debug https://github.com/home-assistant/core/issues/116975 better

Add debug logging

---

setup.py

See breaking change of removing shutdown upon errors at https://github.com/home-assistant-libs/aioshelly/pull/587

Bump version to 11.0.0

---

aioshelly/const.py
aioshelly/rpc_device/device.py

Virtual components docs: https://shelly-api-docs.shelly.cloud/gen2/DynamicComponents/Virtual/

Add support for virtual components

---

aioshelly/rpc_device/device.py
aioshelly/rpc_device/wsrpc.py

#618 prevented battery powered devices from getting the ONLINE message because it did not connect the
the notification callback until after the client websocket init process had completed.
To fix this
- Revert to connecting the notification callback right away
- Only convert notify messages to ONLINE when they are recieved via the server. The client side should never convert notify to ONLINE as it will trigger Home Assistant to try to reconnect again when the connection is already established. This would happen most commonly with BLE notify because the script could still be running during a reconnect which would generate these notify messages before the device had finished initializing.

Fix battery powered devices not getting ONLINE messages

---

aioshelly/rpc_device/wsrpc.py

Save a strong reference to the cleanup task in WsServer

---

aioshelly/rpc_device/wsrpc.py

related issue https://github.com/home-assistant/core/issues/124888

Log method and device ip/port of unknown request ids

---

aioshelly/const.py

https://kb.shelly.cloud/knowledge-base/shelly-plug-s-mtr-gen3
https://kb.shelly.cloud/knowledge-base/shelly-pro-3em-3ct63

Add `Plug S Gen3` and `Pro 3EM 3CT63` models

---

aioshelly/ble/__init__.py
aioshelly/ble/const.py

https://github.com/home-assistant/core/issues/126988#issuecomment-2394259514

Use firmware default BLE scan parameters

---

aioshelly/const.py

Adds definition for Pro 2 v.1 UL

---

aioshelly/const.py

Closes https://github.com/home-assistant-libs/aioshelly/issues/730

Add model ID for Pro 1PM UL (SPSW-201PE15UL)

---

aioshelly/const.py

Add model IDs for 1 Mini Gen4 and 1PM Mini Gen4

---

aioshelly/rpc_device/wsrpc.py

https://github.com/home-assistant-libs/aioshelly/pull/782#issuecomment-2641021225

Guard exceptions in on notification

---

aioshelly/rpc_device/device.py
ruff.toml
tests/rpc_device/conftest.py
tests/rpc_device/test_device.py

Relates to https://github.com/home-assistant/core/issues/137805

Don't assume that `attrs` exists for every dynamic component

---

tests/rpc_device/test_device.py

Add missing tests for 100% coverage for `RpcDevice`:
* [`test_on_notification_no_listener`](diffhunk://#diff-a4a772afd22503a913e0001c1f93af957142b62ab5aae499679c5166271b6bc2R593-R613): Verifies that the `_on_notification` method does not call the listener if it is not set and correctly calls it when added.
* [`test_incorrect_shutdown`](diffhunk://#diff-a4a772afd22503a913e0001c1f93af957142b62ab5aae499679c5166271b6bc2R713-R737): Ensures that multiple shutdown calls in an incorrect order do not cause errors, particularly checking for a `KeyError` during shutdown.

Add tests for RpcDevice notification handling and shutdown order

---

aioshelly/rpc_device/device.py
tests/rpc_device/test_device.py

Related to https://github.com/home-assistant/core/issues/139367

Fix mergedicts to handle None values

---

aioshelly/rpc_device/device.py
tests/rpc_device/test_device.py
tools/common/__init__.py
tools/example.py

https://github.com/home-assistant-libs/aioshelly/pull/792/files#r1958806215

Add support for checking if RPC device supports scripts

---

aioshelly/const.py

https://kb.shelly.cloud/knowledge-base/shelly-az-plug
Relates to https://github.com/home-assistant/core/issues/140471

Add info about AZ Plug

---

.github/workflows/pr-labels.yml

Add PR Labels GH action

---

.devcontainer/Dockerfile
README.md
pyproject.toml
requirements.txt
requirements_dev.txt
requirements_lint.txt
script/environment.sh

Move dependency lists to pyproject.toml file

---

aioshelly/ble/backend/scanner.py
aioshelly/ble/parser.py
pyproject.toml
tests/ble/backend/__init__.py
tests/ble/backend/test_scanner.py
tests/ble/conftest.py
tests/ble/test_init.py
tests/ble/test_parser.py

Some libraries need access to the raw advertising data
see https://github.com/home-assistant/core/issues/143769#issuecomment-2833594159

Migrate shelly to use habluetooth _async_on_raw_advertisement API

---

aioshelly/const.py

Add new model ID for Pro 4PM
