home-assistant-libs/aioshelly

- README.md
- aioshelly/__init__.py
- example.py
This is a breaking change: Now if you want to set a username and password, you first need to create a new ConnectionOptions object.
Introduces a new `ConnectionOptions` object that allows you to define device IP, username, password and preferred temperature unit.
Preferred temperature unit is used to filter out duplicate temperature readings for which both a C and F value exists.
Fixes #7
> [Breaking change] Add support for options object including preferred temperature unit

- aioshelly/__init__.py
For some devices, the sensors are in the block with the description `device` and the `channel` property generates an error:
```
File "/home/maciek/develop/home-assistant-core/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
await asyncio.shield(task)
File "/home/maciek/develop/home-assistant-core/homeassistant/components/shelly/sensor.py", line 116, in async_setup_entry
await async_setup_entry_attribute_entities(
File "/home/maciek/develop/home-assistant-core/homeassistant/components/shelly/entity.py", line 48, in async_setup_entry_attribute_entities
[
File "/home/maciek/develop/home-assistant-core/homeassistant/components/shelly/entity.py", line 49, in <listcomp>
sensor_class(wrapper, block, sensor_id, description, …
```
> Fix channel property when description doesn't contain "_"

- .vscode/settings.json
- aioshelly/__init__.py
Many users complain that the integration doesn't work because they try to configure the device with unsupported firmware. This PR adds a firmware version checking. The library will raise `FirmwareUnsupported` exception if device firmware is unsupported (too old).
> Add firmware version check

- aioshelly/__init__.py
This PR changes the type of CoAP messages that `aioshelly` uses from `CON` to `NON` (from confirmable messages to non-confirmable messages).
I haven't found any downsides to this change and integration works well with it. I have confirmation from several people that after this change, Shelly devices return to the `available` state after power/network failure.
This fix is related with https://github.com/home-assistant/core/issues/40810 and https://github.com/home-assistant/core/issues/40411
> Change the message type from CON to NON

- README.md
- aioshelly/__init__.py
- example.py
This updates the devices to use a shared Coap context instead of each device their own.
**Breaking change:** you now need to pass an `aiocoap_context` when creating a device.
> Use a shared aiocoap context

- aioshelly/__init__.py
This PR adds `semaphore` to ensure maximum one request at a time.
This change will fix issue #6
> Add semaphore to ensure maximum one request at a time

- aioshelly/__init__.py
When shutting down a device, also clear the listener so the object is easier to garbage collect.
> Remove listener on shutdown to help GC

- aioshelly/__init__.py
The CoAP listener needs the device's IP address, so with this change, `aioshelly` will use `socket.gethostbyname` to resolve hostname to IP address. This changed was suggested here https://github.com/home-assistant/core/pull/43963
> Use gethostbyname to resolve hostname to IP address

- README.md
- aioshelly/__init__.py
- example.py
Add `initialize` parameter to `Device.create`, default to `True`
If set to `False` will not initialize device on create but only after `cit/s` CoAP message arrives from the device.
Add new property `initialized` which set to `True` after initialization finished.
Raise `NotInitialized` exception when trying to get value from non-initialized device.
Migrate to `argparse`
> Add support for initializing device when cit/s arrives

- README.md
- aioshelly/coap.py
- mypy.ini
- pylintrc
- requirements.txt
- setup.py
Revert PR: #53, #60
Bump version to 0.6.0
Library is no longer listening on multiple interfaces, only on the default interface. 
Multicast group `224.0.1.188` removed
> Revert multiple interfaces

- aioshelly/coap.py
Change CoAP message parsing log level from error to debug to avoid logging errors for devices which are not Shelly devices and sends CoAP messages.
This PR fixes issue: https://github.com/home-assistant-libs/aioshelly/issues/72
> Fix coap logging

- aioshelly/__init__.py
Force Shelly4Pro and Shelly Sense unsupported firmware message based on device type and not on firmware release date.
Those devices will never get CoAP v2, but still get some firmware update
> Shelly 4Pro and Shelly Sense are unsupported

- aioshelly/__init__.py
Make sure ` self._initialized` is cleared upon exceptions during initialize.
Catch errors when `self.initialize` is called upon CoAP event and log as warning.
> Fix device initialize

- aioshelly/__init__.py
This PR will add a new device method `trigger_ota_update` which allows to trigger an ota update according to https://shelly-api-docs.shelly.cloud/#ota.
Run firmware update from default URL  (`new_version`)
Run firmware update from specified URL
Run firmware update from beta URL (if available)
Still run firmware update from specified URL (_IMHO because url is more specific than beta_)
> Add trigger_ota_update device method

- aioshelly/block_device.py
`BlockDevice` shutdown method was changed to async to be compatible with `RpcDevice` since common `Device` class is removed this is not needed and better changed back to sync
> Revert BlockDevice shutdown to sync

- aioshelly/block_device.py
- aioshelly/common.py
- aioshelly/const.py
Missing timeout has undesirable side effects, like applying default 300s.
This PR add the missing parameter to the affected calls.
> Add missing timeout to client sessions

- aioshelly/coap.py
- example.py
2 new parameters for example.py:
- "`--socket_port`" : allows CoAP port customization.
- "`--debug`": set debug logging level.
> Example.py: allow CoAP port customization and debug logging level

- aioshelly/wsrpc.py
Prevent setting futures resolves during disconnect to prevent the following:
```
2022-01-05 20:05:21 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
File "/usr/local/lib/python3.9/site-packages/aioshelly/wsrpc.py", line 165, in _rx_msgs
self._handle_frame(frame)
File "/usr/local/lib/python3.9/site-packages/aioshelly/wsrpc.py", line 151, in _handle_frame
call.resolve.set_result(frame)
asyncio.exceptions.InvalidStateError: invalid state
```
May also happen during startup if we get a response from the device from previous connection.
> Fix - prevent setting resolves during disconnect or at startup

- aioshelly/wsrpc.py
Add low level communication logging to gen2 (RPC)
During testing I noticed that we start the calls from 2, so changed it to 1.
Logging is not meant to be user friendly, mostly developer friendly.
Example output log:
```
DEBUG:aioshelly.wsrpc:Trying to connect to device at 192.168.1.18
INFO:aioshelly.wsrpc:Connected to 192.168.1.18
DEBUG:aioshelly.wsrpc:send(192.168.1.18): {'id': 1, 'method': 'Shelly.GetDeviceInfo', 'src': 'aios-2184750235312'}
DEBUG:aioshelly.wsrpc:send(192.168.1.18): {'id': 2, 'method': 'Shelly.GetConfig', 'src': 'aios-2184750235312'}
DEBUG:aioshelly.wsrpc:send(192.168.1.18): {'id': 3, 'method': 'Shelly.GetStatus', 'src': 'aios-2184750235312'}
DEBUG:aioshelly.wsrpc:recv(192.168.1.18): {"id":1,"src":"shellyplus1pm-1234567890ab","dst":"aios-2184750235312","result":{"name":" …
```
> Add gen2 communication logging

- setup.py
On the release notes for this version we add the following text:
> Bump version to 1.0.10

- aioshelly/block_device.py
Hi. I am missing some nice features for Shelly devices in Home Assistant, e.g. enabling/disabling Shelly Motion motion detection, setting motion/tamper sensitivity, or changing Shelly Gas Valve addon state. I would like to contribute those to aioshelly and Home Assistant Core. I created this small PR to get a feedback and see the whole process. Thank you.
> Shelly Motion: enable/disable motion detection support.

- .github/release-drafter.yml
Add `breaking-change` section to release drafter, similar to core repository and other repositories in `home-assistant-libs`
> Add breaking change section to release drafter

- .pre-commit-config.yaml
Fixes pre-commit `ImportError: cannot import name '_unicodefun' from 'click'`
> Bump pre-commit black to 22.3.0

- aioshelly/coap.py
**Pad outgoing CoAP requests with 0x00.** 
In KB5015807 (Windows 10) or KB5015814 (Windows 11) a bug introduced by Microsoft causing Hyper-V to drop UDP packets with payload less than 12 bytes. `aioshelly` uses 11 bytes for the `cit/d` request which gets dropped.
Although this is not identified as bug in `aioshelly`, but since it affects large number of installation becoming non operational and some users having trouble to remove the update as it is marked as a security update, this workaround does not have any negative affect as the addional pad with `\x00` (null) does not break the CoAP protocol.
Duo to the importance of this fix I have verified it over 24 Gen1 Shelly models out of 30 active models.
Core related issue: https://github.com/home-assistant/core/issues/75118
> Pad CoAP request with 0x00 to fix Hyper-V issue due to KB5015807

- aioshelly/block_device.py
- aioshelly/const.py
- aioshelly/rpc_device.py
- aioshelly/wsrpc.py
- example.py
This PR copy most of the logic we use in CoAP for Gen1:
- Single server with shared context
- Init device upon receiving a message from the device
- Subscribe for push updates by device IP
To test this on a sleeping device:
- In the device web under `Networks` -> `Outbound websocket` enable the outbound websocket and set URL that points to the host: `ws://<host_ip>:5683/` (note that the `/` at the end is mandatory)
- Run the example : `example.py --ip <device_ip> -g2`
Wait for an update or push the button on the device (when pushing back to sleep device also sends an update)
`RpcDevice.create` requires an additional parameter for the shared inbound websocket server
When creating a device the following:
```python
RpcDevice.create(aiohttp_session, options, init)
```
Should be changed to: …
> Add inbound websocket server for Gen2 sleeping devices

- aioshelly/block_device.py
To avoid `ClientResponseError` exception when the user changes the password for the sleeping device, suppress the exception is necessary.
Related to: https://github.com/home-assistant/core/pull/78786
> Suppress `ClientResponseError` in `update_status()` and `update_settings()`

- aioshelly/block_device.py
- aioshelly/common.py
- aioshelly/const.py
- aioshelly/exceptions.py
- aioshelly/rpc_device.py
- aioshelly/wsrpc.py
- example.py
The following exceptions are no longer raised: 
- `AuthRequired`, use `InvalidAuthError` instead
- `CannotConnect`, `ConnectionFailed`, use `DeviceConnectionError` instead
```python
Use class DeviceConnectionError(ShellyError):
"""Exception indicates device connection errors.""" instead
```
Raised for any device connection related error, one of the following:
```
CONNECT_ERRORS = (
aiohttp.ClientError,
asyncio.TimeoutError,
OSError,
RPCError,
RPCTimeout,
JSONRPCError,
)
```
They are not needed to be handled upstream anymore.
`coap_request` is changed to private (`_coap_request`) this method is not protected by timeout and should not be acceded upstream directly.
Remove default port and update default websocket URL for `WsServer` initialize method.
Move the exceptions and timeout logic …
> Handle exceptions and timeouts inside aioshelly

- aioshelly/const.py
- aioshelly/exceptions.py
- aioshelly/rpc_device.py
- aioshelly/wsrpc.py
Noted by @kzyapkov, if the RPC call contains wrong/incomplete parameters or device could not execute the call for some reason but managed to reply back we have no reason to destroy the connection with the device.
This PR adds a new exception `RpcCallError` which will be raised upon failures to `call_rpc`, However during device initialization if the there is a failure, `DeviceConnectionError` is still raised since in this case this is not due to user or parameter error and we can't continue the device initialization.
> Add RpcCallError exception

- aioshelly/block_device.py
- pylintrc
Add method to set thermostat state (Shelly TRV), to avoid using direct HTTP request in Home Assistant
> Add set thermostat state (Shelly TRV)

- aioshelly/json.py
- aioshelly/wsrpc.py
- requirements.txt
- requirements_lint.txt
with #281 we now process many more websocket
messages. As we do not use the Home Assistant
aiohttp session we need to use orjson manually
to avoid the significant json overhead
> Improve JSON performance

- aioshelly/ble/__init__.py
- aioshelly/rpc_device.py
If the shelly doesn't have BLE enabled and the user turns on the scanner it should just work instead of failing.
supports https://github.com/home-assistant/core/pull/82153
> Add async_ensure_ble_enabled  nd underlying ble_setconfig/ble_getconfig apis

- .pre-commit-config.yaml
`pre-commit` used old `flake8` version from `gitlab` which is no longer available, updated to the latest one using the recommended repo from the docs:
https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework
> Fix pre-commit flake8

- aioshelly/rpc_device/wsrpc.py
Calls were cancelled when the device disconnected which meant anything awaiting them would get CancelledError instead of raising an exception about being disconnected.
We now set the exception to DeviceConnectionError to avoid unexpected cancellation.
The UI in HA now gets `homeassistant.exceptions.HomeAssistantError: Call RPC for shellypluswdus-441793ccbdf4 light_0 connection error, method: Light.Set, params: {'id': 0, 'on': False}, error: DeviceConnectionError()` when the connection drops when trying to turn on/off a dimmer
> Raise exception on disconnect for all inflight calls

- aioshelly/rpc_device/device.py
If we hit a connection or invalid auth error we would clear the _update_listener because it called shutdown which cleared the listener and closed the websocket connection.
We now only shutdown the websocket connection so
updates keep working once we reconnect
> Fix state updates never coming back after reconnect

- tox.ini
Related to https://github.com/home-assistant-libs/aioshelly/pull/306
Add the 3.11 to local `tox` runs
> Add python 3.11 to tox

- aioshelly/block_device/coap.py
- aioshelly/block_device/device.py
- aioshelly/common.py
- aioshelly/json.py
- aioshelly/rpc_device/device.py
- aioshelly/rpc_device/wsrpc.py
- example.py
Add options to subscribe for updates using device MAC (device ID)
Subscribing using device ID will help to support devices behind NAT, proxies, or if device IP changes
Implementation is backward compatible and allow subscribing for updates either by MAC or device IP, we can later drop the support for subscribing by IP.
Closes https://github.com/home-assistant-libs/aioshelly/issues/182
Gen1:
- CoAP contains the device ID in CoAP option 3332, for this parsing of options was added, logic for parsing options is based on https://github.com/chrysn/aiocoap/blob/master/aiocoap/options.py
- For compatibility with older Gen1 devices that only include the last 6 chars of MAC, comparison only compare the last 6 MAC chars
Gen2:
- Device ID is sent on every frame as `src`
Checked on multiple Gen1/Gen2 …
> Add support for subscribing to updates by device MAC

- setup.py
Mainly to include https://github.com/home-assistant-libs/aioshelly/pull/332 since these devices start shipping and we don't have thier model names in `5.2.1`
> Bump version to 5.3.0

- aioshelly/rpc_device/wsrpc.py
- setup.py
Fix race when pinging on closed transport:
```
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
await self._send_frame(message, WSMsgType.PING)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
self._write(header + message)
File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
> Fix ping task - don't ping if transport is closed

- aioshelly/ble/__init__.py
We can use `a2b_base64` since we know the output is always going to be ascii
> Speed up parsing bluetooth advertisement data

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- mypy.ini
- pylintrc
- setup.py
- tox.ini
minor fix for pylintrc
```
pylintrc:1:0: R0022: Useless option value for '--disable', 'abstract-class-little-used' was removed from pylint, see https://pylint.pycqa.org/en/latest/whatsnew/1/1.4.html#what-s-new-in-pylint-1-4-3. (useless-option-value)
```
> Drop Python 3.9 support

- aioshelly/block_device/device.py
- aioshelly/common.py
- aioshelly/exceptions.py
- aioshelly/rpc_device/device.py
- example.py
- pylintrc
Abort connection to device and raise `MacAddressMismatchError` if the supplied MAC address doesn't match the MAC address returned from the device in `/shelly`.
Since we supply the MAC address to allow routing incoming messages we can detect if the IP is wrong and we are connecting to another Shelly device.
I had few IPs mixed up after power failure 
1. Shelly IP mixed with a non Shelly device --> This is not harmful, Init will fail until HA detect the new IP from the device (DHCP/mDNS).
2. Shelly Gen1 IP mixed with Shelly Gen2 IP --> This will raise `WrongShellyGen` which is not handled by HA since it shouldn't happen (runtime error).
3. Shelly IP Mixed with another Shelly from the same Gen --> This creates a bad situation since init succeeds and entities from the one Shelly are added to …
> Abort if input MAC does not match the device MAC

- aioshelly/rpc_device/wsrpc.py
https://docs.python.org/3/library/asyncio-future.html#asyncio.Future
> The rule of thumb is to never expose Future objects in user-facing APIs, and the recommended way to create a Future object is to call loop.create_future(). This way alternative event loop implementations can inject their own optimized implementations of a Future object.
> Create futures with loop.create_future()

- .devcontainer/devcontainer.json
With [November 2023 release of VSCode](https://devblogs.microsoft.com/python/python-in-visual-studio-code-november-2023-release/#deprecated-built-in-linting-and-formatting-features#deprecated-built-in-linting-and-formatting-features), built-in linting and formatting features were deprecated and it is recommended to install the corresponding extensions as replacement.
Also moved settings in the new expected place: [Create a devcontainer.json file](https://code.visualstudio.com/docs/devcontainers/create-dev-container#_create-a-devcontainerjson-file)
> Update devcontainer.json for VScode updated settings

- .github/workflows/test.yml
- setup.py
- tox.ini
I did some tests with Python 3.12 and aiohttp 3.9.0 and everything looks fine.
> Add Python 3.12 to CI

- README.md
- aioshelly/common.py
- aioshelly/const.py
- aioshelly/rpc_device/device.py
- example.py
The API for generation 3 is practically the same as for generation 2, so only minor changes are needed here.
I tested this change with gen1, gen2 and gen3 devices and see no problems.
> Add support for Gen3 devices

- aioshelly/const.py
Firmware 1.0.0 for gen2 devices is a completely new line of software that fixes many problems and introduces many new functionalities. Gen3 devices also use this line of software.
Changelog: https://shelly-api-docs.shelly.cloud/gen2/changelog#100-2023-08-03
Firmware 1.0.0 functionalities related to HA integration:
- Network frequency in status of EM, Switch, Cover components
- New settings for switches - "External consumption type"
- Sys Drop wakeup_period attribute from configuration (deprecated since 0.11.0)
We will be able to remove this method https://github.com/home-assistant/core/blob/c8bb72935d935680ea7a9c5f8bde552f2d8f7dcd/homeassistant/components/shelly/utils.py#L279-L281
> Bump Gen2 minimum firmware version to 1.0.0 (2023-08-03)

- aioshelly/const.py
Due to many fixes and new functionalities introduced in subsequent firmware versions, the minimum firmware version supported by `aioshelly` is increased to 1.11.0 (2021-07-15). This release included the last major change in API functionality (`transition` for lights).
Changelog: https://shelly-api-docs.shelly.cloud/gen1/#changelog
> Bump Gen1 minimum firmware version to 1.11.0 (2021-07-15)

- aioshelly/common.py
- aioshelly/const.py
The last firmware for SHPLG-1 is 1.9.4, and some SHUNI-1 are stuck with firmware `20210105-095645/release-1.9@8517d431+`, so I suggest using 1.9.0 as a minimum, except for bulbs that support light transition, in case these bulbs, the minimum firmware remains at version 1.11.0.
Related to: https://github.com/home-assistant/core/issues/107352
> Change the minimum supported gen1 firmware to 1.9.0

- aioshelly/ble/const.py
80 proved to be to large to avoid running out of memory
> Lower BLE 2.0 script max queue size to 32

- .pre-commit-config.yaml
CI runs `pylint`, but we don't locally.
This PR address this deficiency
> Add pylint to pre-commit

- example.py
If there is no initial device init (battery powered devices), then we need to specify device generation.
> Check args for gen when there is no initial inint

- aioshelly/block_device/device.py
Since last week I have some failures with Gen1 devices, I still don't know if this is related to the transition to Python 3.12, a problem in my network or device problem. I suspect something happens faster and devices with ECO mode enabled fail to respond.
However even if it is a network or device problem, adding a single retry can improve the situation. We had many users complaining about failed actions, mainly to sleepy devices such as Shelly TRV & Shelly Motion.
I didn't increase the timeout, the retry still happen within our current timeout (10 seconds). For the last few days I had 33 retry occurrences and they all succeeded (meaning a single retry was enough, and without it 33 actions would fail). 
Retry will cause a short delay in action (up to two seconds) but is still acceptable …
> Add retry to Block HTTP requests

- aioshelly/block_device/coap.py
- aioshelly/const.py
Home Assistant allows users to specify the internal network they want to use.
This makes integrations listen on that specific adapter instead of 0.0.0.0.
This PR allows to specify a IP address for CoAP listening, while not chancing current behaviour.
Fixes #149
> Allow setting of CoAP listening IP address

- aioshelly/block_device/device.py
- aioshelly/rpc_device/device.py
> Important Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection:
> Save strong reference to create_task

- aioshelly/ble/__init__.py
- aioshelly/block_device/device.py
- aioshelly/common.py
- aioshelly/exceptions.py
- aioshelly/rpc_device/device.py
- aioshelly/rpc_device/wsrpc.py
- tools/common/__init__.py
- tools/example.py
(Will rebase when https://github.com/home-assistant-libs/aioshelly/pull/324 is merged)
Enables support for Range Extender connected Gen2 devices (following request to use port as a parameter in https://github.com/home-assistant-libs/aioshelly/pull/322).
Unfortunately, it looks like CoAP is not possible due to Range Extender only forwarding to port 80 on the device. If my understanding is incorrect I'd be happy to try and incorporate support for Gen1 devices as well.
If this PR is accepted, there will need to be additional work to the Home Assistant configuration flow to specify ports.
> Add support for specifying port in Gen2 devices

- tools/example.py
Remove background noise from logging when debug option is enabled.
**Background**:
When you are debugging gen2, having all debug traffic from gen1 is just filling quickly the window making easy to miss what you need.
And the other way around with gen2.
**Solution**:
So if you specify a gen as arg, and only on that case, you just lower the logging for others gen in order to focus on what you are looking for
> Simplify logging during debugging

- .github/workflows/test.yml
I suggest replacing `pip` with `uv` for `tox`, which speeds up the process of testing commits.
When `pip` is used to install requirements for `tox`, we need about 50 seconds
If we switch to `uv`, we only need 20 seconds
> Use `uv` with `tox`

- .github/workflows/pre-commit-update.yml
Currently, we very rarely update the version of pre-commit hooks. For example, the `ruff` and `mypy` hooks are currently not up-to-date. I suggest adding GH action, which will run `pre-commit autoupdate` once a week and open PR if updates are available.
> Add pre-commit autoupdate GH action

- aioshelly/ble/const.py
Shelly is getting reports from users not able to delete a specific script and suggested to add a comment on top of the script body stating clearly that it is installed by HA
> Add comment to explain the usage of the aioshelly BLE script

- aioshelly/rpc_device/device.py
The RPC shutdown process is not reversible since there is no method to reconnect the websocket.
Remove the comment to avoid incorrectly trying to reverse shutdown.
> Update RPC shutdown description

- aioshelly/block_device/device.py
- aioshelly/rpc_device/device.py
- tools/common/__init__.py
- tools/example.py
- tools/fixture.py
Remove background `_async_init` task and `initialize` parameter:
- Move call to `initialize` for sleeping devices to user code, `_async_init` is no longer runs inside `aioshelly` which allows the user to call `initialize` when device is online and catch the errors.
- Add new status update type: `BlockUpdateType.ONLINE` & `RpcUpdateType.ONLINE` which inform the user that the device is online and he can call the `initialize`.
- Remove `initialize` parameter from device create. User is responsible to call `initialize`. This helps that we don't need to catch errors in two different places and can catch errors only on `initialize` method.
- Update examples
In the future we can use mDNS advertising from the device to call `initialize` which will help setting up sleeping devices which doesn't …
> Move call to initialize to user code

- README.md
- aioshelly/block_device/device.py
- aioshelly/common.py
- aioshelly/const.py
- aioshelly/exceptions.py
- aioshelly/rpc_device/device.py
- tools/common/__init__.py
Allow initialization of a device with unsupported firmware so that we can use the device to trigger an update.
Added property to indicate if firmware is supported (`firmware_supported`)
Updated the `example.py` to indicate if firmware is not supported:
<ins>Gen1:</ins>
```
** shelly4pro-801234 - Shelly 4Pro  @ 192.168.1.49:80**
Device firmware not supported: 20190821-095050/v1.5.2@4148d2b7
```
<ins>Gen2:</ins>
```
** shellyplus1-a8032abe1234 - Shelly Plus 1  @ 192.168.1.70:80**
Device firmware not supported: 20210714-140932
```
(this Shelly pre-production firmware doesn't have a version only a date)
> Allow initialization for device with unsupported firmware

- aioshelly/block_device/device.py
- tools/common/__init__.py
- tools/example.py
Align device shutdown method so both block device and RPC device methods will be async, this makes it easier that devices has common interface (`create`, `initialize`, `subscribe_updates` & `shutdown`)
For block device the method was changed to `async`, it should be awaited now.
```python
device.shutdown()
```
```python
await device.shutdown()
```
Example code updated to call shutdown upon `ctrl-c` so we can test device shutdown.
> Align device shutdown

- aioshelly/block_device/device.py
- aioshelly/rpc_device/device.py
- setup.py
Fix https://github.com/home-assistant/core/issues/118898
When a device status is updated while it is disconnected and we reconnect to the device we the status is not updated since we already have a status (this logic is needed for sleeping devices).
This makes sure that if we re-init a device we also fetch new status from it.
> Fetch new status on device re-init

- aioshelly/block_device/device.py
- aioshelly/rpc_device/device.py
This PR removes the calls to `shutdown` (Gen1) and `self._disconnect_websocket()` (same as `shutdown`, Gen2+) upon failures.
The `shutdown` process removes subscription to device async updates (updates which are pushed from the device by IP/MAC), this method is not reversible so after calling shutdown the only way to resubscribe to updates is to create a new device object.
However for sleeping devices we need the updates to continue flowing even if there is a failure since they trigger event to connect to the device.
Currently, If a sleeping device has an error on first time that we try to connect to it and it fails subsequent events from the device will be stopped so there won't be anything to try to trigger a new connection to the device on the next wakeup.
This logic was existing up to …
> Do not shutdown device upon errors

- aioshelly/block_device/device.py
- aioshelly/common.py
Calling timeout with float is deprecated, and the typing now reflects the deprecation. use aiohttp.ClientTimeout instead
> Use aiohttp.ClientTimeout for passing timeouts

- aioshelly/const.py
- aioshelly/rpc_device/device.py
Related to https://github.com/home-assistant/core/issues/123440
The integration uses `component_added` and `component_removed` events so firmware 1.2.0 is the minimum version to ensure full compatibility with virtual components.
Tested with firmware 1.1.0 and 1.2.0.
> Don't use `GetComponents` if firmware doesn't support it

- aioshelly/rpc_device/device.py
There is already a timeout in wsrpc.call
> Fix duplicate timeout in call_rpc

- aioshelly/rpc_device/device.py
- requirements_dev.txt
- ruff.toml
- tests/__init__.py
- tests/rpc_device/__init__.py
- tests/rpc_device/test_device.py
- tox.ini
I noticed the dict merge makes two copies of the destination dict, one inside `mergedicts` and one outside.  It doesn't look like we need to make a make a copy in the first place since we never compare the old and new data anywhere.
This is a ~92% speed up
> Optimize RPC device dict merge

- aioshelly/rpc_device/device.py
Attempt to fix: https://github.com/home-assistant/core/issues/123399#issuecomment-2294924493
> Block notifications if the device is not initialized

- aioshelly/rpc_device/device.py
- aioshelly/rpc_device/wsrpc.py
Currently all calls during the websocket reconnect process happened in sequence:
send -> wait -> read -> send -> wait -> read -> send -> wait -> read ...
This pattern results in the reconnect process taking a bit longer.
We can now send multiple calls and await for their responses:
send all -> wait all -> read all
This is not implemented as parallel tasks as there is a chance we need to retry requests if auth needs to be recalculated
> Add support for parallel rpc calls

- aioshelly/rpc_device/device.py
This will fix WallDisplay support with authorization enabled. WallDisplay doesn't return `auth_domain` value in response to `/shelly`.
> Use `device_id` as `realm` value for auth

- aioshelly/rpc_device/device.py
- aioshelly/rpc_device/wsrpc.py
Avoid the REST call since we have to create another connection to the device when we do the rest call which will stay open for a bit. By doing everything of the websocket we put less pressure on the device, and setup is a bit faster
> Switch fetching device info to go over the websocket for RPC devices

- aioshelly/const.py
- aioshelly/rpc_device/device.py
- aioshelly/rpc_device/wsrpc.py
In https://github.com/home-assistant/core/issues/124888 we see that GetStatus can take up to 22+ seconds to respond.
```
2024-08-30 01:12:02.409 DEBUG (MainThread) [aioshelly.rpc_device.wsrpc] send(192.168.88.31:80): {'id': 760, 'method': 'Shelly.GetStatus', 'src': 'aios-139875229921600', 'dst': 'shellyplus2pm-48551998da98'}
```
```
2024-08-30 01:12:24.672 DEBUG (MainThread) [aioshelly.rpc_device.wsrpc] recv(192.168.88.31:80): {'id': 760, 'src': 'shellyplus2pm-48551998da98', 'dst': 'aios-139875229921600', 'result': {'ble': {}, 'cloud': {'connected': False}, 'input:0': {'id': 0, 'state': True}, 'input:1': {'id': 1, 'state': False}, 'mqtt': {'connected': False}, 'script:1': {'id': 1, 'running': False, 'mem_free': 25200}, 'switch:0': {'id': 0, 'source': 'switch', 'output': False, 'apower': …
```
> Use extended timeouts for status calls that may take a while

- aioshelly/block_device/device.py
- aioshelly/common.py
- aioshelly/const.py
- aioshelly/exceptions.py
- aioshelly/rpc_device/wsrpc.py
- tools/common/__init__.py
When `DeviceConnectionError` is raised, its not immediately obvious that when its a timeout problem.
`DeviceConnectionTimeoutError` is a subclass of `DeviceConnectionError` to ensure backwards compat.
related issue https://github.com/home-assistant/core/issues/124888
> Add a separate timeout error exception class

- aioshelly/const.py
Adding this new device:
https://www.shelly.com/products/shelly-dali-dimmer-gen3
https://shelly-api-docs.shelly.cloud/gen2/Devices/Gen3/ShellyDDimmerG3
> Add Shelly DALI Dimmer Gen3

- .github/workflows/test.yml
- setup.py
- tox.ini
I'm testing aioshelly with Python 3.13 and https://github.com/home-assistant/core/pull/129442
So far everything looks good
> Add Python 3.13 to CI

- aioshelly/json.py
- aioshelly/rpc_device/wsrpc.py
- requirements.txt
> Update WebSocket sender to avoid extra utf-8 decode/encode round-trip

- aioshelly/rpc_device/device.py
Fixes regression found at https://github.com/home-assistant/core/issues/130696
> Fix MacAddressMismatchError check for RPC devices

- setup.py
otherwise it tries to install a package called 'tests' at top level, this is forbidden:
```
>>> Emerging (1 of 1) dev-python/aioshelly-12.0.1::HomeAssistantRepository
>>> Failed to emerge dev-python/aioshelly-12.0.1, Log file:
>>>  '/var/tmp/portage/dev-python/aioshelly-12.0.1/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.69, 0.27, 0.12
* Package:    dev-python/aioshelly-12.0.1:0
* Repository: HomeAssistantRepository
* Maintainer: b@edevau.net
* Upstream:   paulus@home-assistant.io
* USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_12
* FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking aioshelly-12.0.1.tar.gz to /var/tmp/portage/dev-python/aioshelly-12.0.1/work
>>> …
```
> Exclude tests from package build

- setup.py
Related to https://github.com/home-assistant-libs/aioshelly/pull/705
> Restore use of `find_packages` in setup.py

- aioshelly/const.py
Output from `/shelly`:
```
{"name":null,"id":"shelly3em63g3-redacted","mac":"redacted","slot":1,"model":"S3EM-003CXCEU63","gen":3,"fw_id":"20241114-135317/1.4.99-3emg3prod1-g2299489","ver":"1.4.99-3emg3prod1","app":"S3EMG3","auth_en":false,"auth_domain":null,"profile":"triphase"}
```
> Add Shelly 3EM-63 Gen3 model

- aioshelly/rpc_device/wsrpc.py
```
2024-12-30 19:44:45.247 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
File "/usr/local/lib/python3.13/site-packages/aioshelly/rpc_device/wsrpc.py", line 345, in _rx_msgs
msg = await self._client.receive()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/aiohttp/client_ws.py", line 376, in receive
await self.pong(msg.data)
File "/usr/local/lib/python3.13/site-packages/aiohttp/client_ws.py", line 232, in pong
await self._writer.send_frame(message, WSMsgType.PONG)
File "/usr/local/lib/python3.13/site-packages/aiohttp/_websocket/writer.py", line 125, in send_frame
raise ClientConnectionResetError("Cannot write to closing transport") …
```
> Catch one more connection exception

- aioshelly/rpc_device/device.py
Fixes https://github.com/home-assistant-libs/aioshelly/issues/674
> Get all response pages for Shelly.GetComponents

- aioshelly/rpc_device/device.py
We can drop `GetRemoteStatus` and use the status from `GetComponents` response.
All needed data is in the `GetComponents` response
> Use the status from `GetComponents` instead of `GetRemoteStatus`

- aioshelly/rpc_device/device.py
When I call `BluTRV.Call` via `call_rpc` from an integration sometimes the requests ends with `DeviceConnectionError` because the timeout is too short for BLU TRV. I suggest to add `timeout` parameter for `call_rpc` method and pass it to the `call_rpc_multiple` method.
> Add `timeout` parameter for `call_rpc` method

- ruff.toml
Add notes for ruff ignored rules that conflicts with other rules so we don't get back to them every time, we try to cleanup ignored rules, related to https://github.com/home-assistant-libs/aioshelly/pull/769
> Add notes for ruff ignored rules that conflicts with other rules

- aioshelly/rpc_device/device.py
This will allow us to map `attrs.role` to the device class for Powered by Shelly devices.
> Add `attrs` from dynamic component to the `config`

- aioshelly/rpc_device/device.py
Fixes `KeyError` when `rssi` and `uptime` sensors are enable for BLU Gateway
```
2025-02-06 15:13:59.755 DEBUG (MainThread) [aioshelly.rpc_device.wsrpc] send(192.168.2.210:80): {'id': 12, 'method': 'Shelly.GetComponents', 'src': 'aios-140615453547488', 'params': {'dynamic_only': True}, 'dst': 'shellyblugwg3-34cdb078742c', 'auth': {'realm': 'shellyblugwg3-34cdb078742c', 'username': 'admin', 'nonce': 1738849439, 'cnonce': 1738851239, 'response': '6849f9f88eef4ebb4c22c0e4d1948a1c371432d137688b75232c1097ec614a22', 'algorithm': 'SHA-256'}}
2025-02-06 15:13:59.760 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
File "/home/maciek/develop/home-assistant-core/venv/lib/python3.13/site-packages/aioshelly/rpc_device/wsrp …
```
> Update status instead of overwriting it when pooling

- aioshelly/rpc_device/device.py
- tests/rpc_device/test_device.py
We still need to raise a `WrongShellyGen` exception for Gen1 devices since the `/shelly` endpoint is available for all generations.
> Do not raise `WrongShellyGen` in `RpcDevice`

- aioshelly/ble/const.py
This single return statement with the missing semicolon seems inconsistent with the rest of the script and Shelly's scripting language isn't exactly JavaScript. Some older version thereof even said semicolons are mandatory. This PR is therefore adding the missing semicolon.
> Fix missing semicolon in BLE Script

- aioshelly/rpc_device/__init__.py
- aioshelly/rpc_device/utils.py
- tests/rpc_device/test_init.py
- tests/rpc_device/test_utils.py
Add `bluetooth_mac_from_primary_mac` which accepts the primary MAC and returns the Bluetooth MAC
The MAC must be in the format `[0-F]{16}`
> Add support for getting the bluetooth MAC form the primary MAC

- aioshelly/ble/__init__.py
- requirements.txt
- tests/ble/__init__.py
- tests/ble/test_init.py
We want `habluetooth` to be able to make better decisions about routing advertisement data, however we currently don't know if a shelly scanner is in passive or active mode so this is not possible.
> Add support for passing the BluetoothScanningMode to the scanner

- aioshelly/rpc_device/device.py
- tests/rpc_device/test_device.py
Better alternative to https://github.com/home-assistant-libs/aioshelly/pull/840, instead of reading the whole script, read only 1 byte from the script, related to https://github.com/home-assistant/core/issues/142190#issuecomment-2779662995.
Tested with:
- Shelly Pro 2PM
- Shelly Wall Display X2
- LinkedGo ST1820
> Read 0 bytes when checking for script support

- tests/block_device/__init__.py
- tests/block_device/conftest.py
- tests/block_device/test_device.py
- tests/block_device/test_init.py
Create initial tests for block_device module, this mainly so that code is imported, only two tests added but now we can expand coverage by adding more tests.
> Add initial tests for block_device module

- pyproject.toml
This version is already required but since we pin it in HA and we don't use the ble code directly outside of HA it likely hasn't been a problem
changelog: https://github.com/Bluetooth-Devices/bluetooth-data-tools/compare/v1.19.0...v1.28.0
> Bump bluetooth-data-tools to 1.28.0

- aioshelly/const.py
1L Gen3
```json
{
"name": "null",
"id": "shelly1lg3-xxxxxxxxxxxx",
"mac": "XXXXXXXXXXXX",
"slot": 1,
"model": "S3SW-0A1X1EUL",
"gen": 3,
"fw_id": "20250319-150640/1.6.99-xlg3prod0-g1c18aaa",
"ver": "1.6.99-xlg3prod0",
"app": "S1LG3",
"auth_en": false,
"auth_domain": null
}
```
2L Gen3
```json
{
"name": null,
"id": "shelly2lg3-xxxxxxxxxxxx",
"mac": "XXXXXXXXXXXX",
"slot": 0,
"model": "S3SW-0A2X4EUL",
"gen": 3,
"fw_id": "20250508-110809/1.6.1-g8dbd358",
"ver": "1.6.1",
"app": "S2LG3",
"auth_en": false,
"auth_domain": null,
"matter": false
}
```
> Add model IDs for 1L Gen3 and 2L Gen3

- aioshelly/block_device/device.py
- aioshelly/const.py
**Shelly Gen1 changelog:**
Requesting `cit/d` for Block devices introduced at firmware v1.10 (released at 02.03.2021), currently we still support devices with firmware v1.9:
https://github.com/home-assistant-libs/aioshelly/blob/8df2cdea1d0e947d986da43e46418fe433c9f714/aioshelly/const.py#L148-L149
Mainly due to some of them not having a newer firmware, such as Shelly Plug 1 - latest firmware is v.1.9.4, related to https://github.com/home-assistant/core/issues/148607
This PR checks that the firmware at least at v1.10 for using HTTP `cit/d` requests and fallback to `CoAP` `cit/d` for older devices.
Tested with:
- Shelly Plug 1 with firmware v1.9.4 (latest, fallback)
- Shelly 1 with firmware v1.9.4 (fallback)
- Shelly 1 with firmware v1.10.1 (http)
- Shelly 1 with firmware v1.14.0 (latest, …
> Fix Block device cit/d for older firmware versions

- aioshelly/rpc_device/device.py
- tests/rpc_device/test_device.py
Add button_trigger method to RpcDevice which is required for supporting the button virtual component:
https://shelly-api-docs.shelly.cloud/gen2/DynamicComponents/Virtual/Button#buttontrigger
This is already in use by FrankEver Smart water valve - https://www.shelly.com/products/frankever-smart-water-valve-fk-v02t
Home Assistant:
```json
{
"key": "button:200",
"status": {
},
"config": {
"id": 200,
"name": "Close",
"meta": {
"ui": {
"view": "button"
}
},
"owner": "service:0",
"access": "crw"
},
"attrs": {
"owner": "service:0",
"role": "close"
}
},
{
"key": "button:201",
"status": {
},
"config": {
"id": 201,
"name": "Open",
"meta": {
"ui": {
"view": "button"
}
},
"owner": "service:0",
"access": "crw"
},
"attrs": {
"owner": "service:0",
"role": "open"
}
},
```
> Add button_trigger method to RpcDevice

- aioshelly/const.py
```json
{
"name": "Shelly Duo Bulb Gen3 [DDEEFF]",
"id": "shellyduobulbg3-aabbccddeeff",
"mac": "AABBCCDDEEFF",
"slot": 0,
"model": "S3BL-D010009AEU",
"gen": 3,
"fw_id": "20250909-133941/i4g4zb_certification_iteration_0-99-g1d070a496-main",
"ver": "1.8.99",
"app": "DuoBulbG3",
"auth_en": true,
"auth_domain": "shellyduobulbg3-AABBCCDDEEFF"
}
```
> Add model info for Duo Bulb Gen3
